### PR TITLE
url-icon

### LINKED ISSUE #15: Update icon/logo links

### PR DESCRIPTION
**Pull request by arul21**
Fixes #15

### CODE REVIEW

**Comment by ADI10HERO** [comment]
Thank you so much @arul21

**Comment by arul21** [comment]
sure @ADI10HERO

**Comment by arul21** [comment]
> Thank you so much @arul21

sure

**Comment by arul21** [comment]
kenapa kamu tidak memberi label hacktoberfest & hacktoberfest-accepted ? @ADI10HERO

**Comment by arul21** [comment]
why don't you label hacktoberfest & hacktoberfest-accepted ? @ADI10HERO

**Comment by ADI10HERO** [comment]
Hey @arul21, as the repository has hacktoberfest topic, you don't need to label PRs separately.

**Pull request merged**
